version: "0.001"

services:
  dht:
    image: sillyvain/volentixlabs:0.0.4
    container_name: dht
  
    ports:
      - "1197:1197"
    
    entrypoint: "bash -c \"\ 
    
    cd tools && \
    ./dhtnode -p 1197 &&\
    sleep 5d  
       \""

  dht1:
    image: sillyvain/volentixlabs:0.0.4
    container_name: dht1
    ports:
      - "1198:1198"
    
    entrypoint: "bash -c \"\ 
    cd tools && \
    ./dhtnode -p 1198 && \
    sleep 5d  
       \""
    
  client1:
    image: sillyvain/volentixlabs:0.0.4
    container_name: client1

    ports:
      - "1199:1199"
    
    entrypoint: "bash -c \"\
   
      g++ main.cpp -std=c++11 -lopendht -lgnutls && \   
     ./a.out && \
      sleep 5d  
       \""

    